import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Password bank",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className="h-full"
			suppressHydrationWarning
		>
			<body className={`${geistSans.variable} ${geistMono.variable} flex min-h-full flex-col antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
				>
					{children}
				</ThemeProvider>
				<Toaster />
			</body>
		</html>
	)
}
